version: "3.8"

networks:
  networkOne:
      driver: bridge

services:
  todo-web:
    ports: 
      - 5000:5000
    build: ./apps/web
    networks:
      - networkOne

  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'todo_schema'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - networkOne

  todo-api:
    depends_on:
      - mysql
    ports: 
      - 3000:3000
    build: ./apps/api
    env_file:
      - ./apps/api/.env.dev  # Specify the path to the .env.local file
    environment:
      - DB_PORT=3306
      - DB_HOST='mysql'
    networks:
      - networkOne